// <auto-generated />
namespace FPCS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07_12_2017_00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07_12_2017_00));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071030449_07_12_2017_00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
