//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPCS.Web.Admin.TFOMS_OUT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FLK", Namespace="")]
    [System.SerializableAttribute()]
    public partial class FLK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNAME_IField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FPCS.Web.Admin.TFOMS_OUT.PR[] PRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FNAME {
            get {
                return this.FNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FNAMEField, value) != true)) {
                    this.FNAMEField = value;
                    this.RaisePropertyChanged("FNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FNAME_I {
            get {
                return this.FNAME_IField;
            }
            set {
                if ((object.ReferenceEquals(this.FNAME_IField, value) != true)) {
                    this.FNAME_IField = value;
                    this.RaisePropertyChanged("FNAME_I");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FPCS.Web.Admin.TFOMS_OUT.PR[] PR {
            get {
                return this.PRField;
            }
            set {
                if ((object.ReferenceEquals(this.PRField, value) != true)) {
                    this.PRField = value;
                    this.RaisePropertyChanged("PR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PR", Namespace="")]
    [System.SerializableAttribute()]
    public partial class PR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BAS_ELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IM_POLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string N_ZAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSHIBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_EL {
            get {
                return this.BAS_ELField;
            }
            set {
                if ((object.ReferenceEquals(this.BAS_ELField, value) != true)) {
                    this.BAS_ELField = value;
                    this.RaisePropertyChanged("BAS_EL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENT {
            get {
                return this.COMMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMENTField, value) != true)) {
                    this.COMMENTField = value;
                    this.RaisePropertyChanged("COMMENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IM_POL {
            get {
                return this.IM_POLField;
            }
            set {
                if ((object.ReferenceEquals(this.IM_POLField, value) != true)) {
                    this.IM_POLField = value;
                    this.RaisePropertyChanged("IM_POL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string N_ZAP {
            get {
                return this.N_ZAPField;
            }
            set {
                if ((object.ReferenceEquals(this.N_ZAPField, value) != true)) {
                    this.N_ZAPField = value;
                    this.RaisePropertyChanged("N_ZAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSHIB {
            get {
                return this.OSHIBField;
            }
            set {
                if ((object.ReferenceEquals(this.OSHIBField, value) != true)) {
                    this.OSHIBField = value;
                    this.RaisePropertyChanged("OSHIB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TfomsZipFile", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class TfomsZipFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file {
            get {
                return this.fileField;
            }
            set {
                if ((object.ReferenceEquals(this.fileField, value) != true)) {
                    this.fileField = value;
                    this.RaisePropertyChanged("file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((object.ReferenceEquals(this.filenameField, value) != true)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TFOMS_OUT.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImportResult", ReplyAction="http://tempuri.org/IService1/GetImportResultResponse")]
        FPCS.Web.Admin.TFOMS_OUT.FLK GetImportResult(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImportResult", ReplyAction="http://tempuri.org/IService1/GetImportResultResponse")]
        System.Threading.Tasks.Task<FPCS.Web.Admin.TFOMS_OUT.FLK> GetImportResultAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTfomsFile", ReplyAction="http://tempuri.org/IService1/InsertTfomsFileResponse")]
        FPCS.Web.Admin.TFOMS_OUT.FLK InsertTfomsFile(FPCS.Web.Admin.TFOMS_OUT.TfomsZipFile tfomsZipFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTfomsFile", ReplyAction="http://tempuri.org/IService1/InsertTfomsFileResponse")]
        System.Threading.Tasks.Task<FPCS.Web.Admin.TFOMS_OUT.FLK> InsertTfomsFileAsync(FPCS.Web.Admin.TFOMS_OUT.TfomsZipFile tfomsZipFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FPCS.Web.Admin.TFOMS_OUT.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FPCS.Web.Admin.TFOMS_OUT.IService1>, FPCS.Web.Admin.TFOMS_OUT.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FPCS.Web.Admin.TFOMS_OUT.FLK GetImportResult(string fileName) {
            return base.Channel.GetImportResult(fileName);
        }
        
        public System.Threading.Tasks.Task<FPCS.Web.Admin.TFOMS_OUT.FLK> GetImportResultAsync(string fileName) {
            return base.Channel.GetImportResultAsync(fileName);
        }
        
        public FPCS.Web.Admin.TFOMS_OUT.FLK InsertTfomsFile(FPCS.Web.Admin.TFOMS_OUT.TfomsZipFile tfomsZipFile) {
            return base.Channel.InsertTfomsFile(tfomsZipFile);
        }
        
        public System.Threading.Tasks.Task<FPCS.Web.Admin.TFOMS_OUT.FLK> InsertTfomsFileAsync(FPCS.Web.Admin.TFOMS_OUT.TfomsZipFile tfomsZipFile) {
            return base.Channel.InsertTfomsFileAsync(tfomsZipFile);
        }
    }
}
